name = "PhilipsWorkspace"
uuid = "a5223014-48d4-4ad6-9e99-a590982f2972"
authors = ["Oscar van der Heide <o.vanderheide@umcutrecht.nl> and contributors"]
version = "0.1.2"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1.10"
JSON = "0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
